apiVersion: apps/v1
kind: Deployment
metadata: 
 name: order
 namespace: nagp
 labels:
  app: order
spec:
 replicas: 1
 selector:
  matchLabels:
   app: orderservice
 template:
  metadata:
   labels:
    app: orderservice
  spec:
   containers:
    - name: order
      image: girishsuri/order:3
      env:
      - name: MYSQL_PASSWORD
        valueFrom:
         secretKeyRef:
          name: mysql
          key: password 
      - name: Jaeger_Collector_Host
        value: http://jaeger-collector.default.svc.cluster.local:14268/api/traces
      - name: MYSQl_HOST
        value: mysql.default.svc.cluster.local
      ports:
        - containerPort: 3000